name: Test and Deploy 

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 22.x
              uses: actions/setup-node@v2
              with: 
                node-version: '22'
                cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Build and Deploy 
              uses: omkartapale/react-deployment-gh-pages@v1.0.0

        
